
import javax.swing.ButtonGroup;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dhwani
 */
public class GroceryAndStaples_not_useful extends javax.swing.JFrame {

    /**
     * Creates new form GroceryAndStaples
     */
    public GroceryAndStaples_not_useful() {
        initComponents();
        ButtonGroup GroceryandStaples = new ButtonGroup();
        GroceryandStaples.add(jRadioButton1);
        GroceryandStaples.add(jRadioButton2);
        GroceryandStaples.add(jRadioButton3);
        GroceryandStaples.add(jRadioButton4);
        GroceryandStaples.add(jRadioButton5);
        GroceryandStaples.add(jRadioButton6);
        GroceryandStaples.add(jRadioButton7);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jRadioButton7.setText("jRadioButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jRadioButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jRadioButton1.setText("DryFruits And Nuts");
        jRadioButton1.setOpaque(false);
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(82, 69, 189, 35);

        jRadioButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Flours");
        jRadioButton2.setOpaque(false);
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(82, 107, 77, 35);

        jRadioButton3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jRadioButton3.setText("Oil and Ghee");
        jRadioButton3.setOpaque(false);
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(82, 145, 129, 35);

        jRadioButton4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jRadioButton4.setText("Pastes");
        jRadioButton4.setOpaque(false);
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(82, 180, 79, 35);

        jRadioButton6.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jRadioButton6.setText("Pulses");
        jRadioButton6.setOpaque(false);
        getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(82, 215, 77, 35);

        jRadioButton9.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jRadioButton9.setText("Rice");
        jRadioButton9.setOpaque(false);
        getContentPane().add(jRadioButton9);
        jRadioButton9.setBounds(82, 250, 61, 35);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel1.setText("Grocery And Staples");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 10, 231, 47);

        jRadioButton5.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jRadioButton5.setText("Spices");
        jRadioButton5.setOpaque(false);
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(82, 285, 79, 35);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Krogers1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 60, 380, 278);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onlinegroceryshopping/Back.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 350, 70, 70);

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onlinegroceryshopping/Next.jpg"))); // NOI18N
        getContentPane().add(jButton2);
        jButton2.setBounds(290, 350, 70, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Departments().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroceryAndStaples_not_useful.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroceryAndStaples_not_useful.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroceryAndStaples_not_useful.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroceryAndStaples_not_useful.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GroceryAndStaples_not_useful().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton9;
    // End of variables declaration//GEN-END:variables
}
