import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dhwani
 */
public class MyCart extends javax.swing.JFrame {
 public static String dppath = "E:/Night_Fury/Sem 4/JAVA/OnlineGroceryShopping/java.accdb";
    public static Connection con = null;
    public static Statement s = null;
    public static ResultSet rs = null;
    /**
     * Creates new form AddToCart
     */
    public MyCart() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        try{
            Connection con = DriverManager.getConnection("jdbc:ucanaccess://" + dppath);
            Statement st = con.createStatement();
            String str = "Select * from Cart AS c INNER JOIN Item_Purchase AS i ON c.Item_Name = i.Item_Name";
            rs = st.executeQuery(str);
            System.out.println(str);
            int i = 0;
            float sum;
                while(rs.next())
                {
                    System.out.println(rs.getString("Item_Name"));
                    
                    
                    //String tempstr = "Select * from Cart";
                    //ResultSet temprs = st.executeQuery(str);
                    
                    java.awt.Label itemLabel = new java.awt.Label();
                    itemLabel.setAlignment(java.awt.Label.CENTER);
                    itemLabel.setBackground(new java.awt.Color(255, 255, 255));
                    itemLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
                    itemLabel.setText(rs.getString("Item_Name")+"(Rs "+rs.getString("Price")+")");
                    jPanel1.add(itemLabel);
                    itemLabel.setBounds(190,(i*25)+70,320,25);
                    jPanel1.add(itemLabel);
                    //sum = sum + price
                    /*String str1 = "Select Price from Item_Purchase WHERE Item_Name = "+rs.getString("Item_Name")+";";
                    rs = st.executeQuery(str1);
                    jPanel1.setText(rs.)*/
                    i++;
                }
                System.out.println("123");
                str = "SELECT Sum(price) AS TOT_price\n" +
                        "FROM Item_Purchase\n" +
                            "WHERE (((Item_Purchase.[Item_Name]) In (select Item_Name from Cart)));";
                System.out.println(str);
                //System.out.println("456");
                rs=st.executeQuery(str);
                rs.next();
                jLabel2.setText(rs.getString("TOT_price"));
                //System.out.println("456");
               // System.out.println(rs.getString("TOT_price"));
               // System.out.println("456");
                //System.out.println(rs.getString("TOT_price"));               
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        button1 = new java.awt.Button();
        jPanel1 = new javax.swing.JPanel();
        label3 = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(255, 255, 255));
        label1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        label1.setText("My Cart");
        getContentPane().add(label1);
        label1.setBounds(223, 10, 241, 56);

        button1.setBackground(new java.awt.Color(255, 255, 255));
        button1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        button1.setLabel("Proceed To check Out");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1);
        button1.setBounds(436, 374, 230, 34);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(new java.awt.Color(255, 255, 255));
        label3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        label3.setText("View Total Price");
        jPanel1.add(label3);
        label3.setBounds(250, 300, 137, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 100, 690, 210);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 330, 80, 40);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setText("Total :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 330, 90, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new CheckOut().setVisible(true);
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyCart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label3;
    // End of variables declaration//GEN-END:variables
}
